apiVersion: v1
kind: Service
metadata:
  name: devops-jenkins-ci-cd
spec:
  selector:
    app: devops-jenkins-ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30544
  #type: ClusterIP
  type: NodePort